### ISSUE TITLE
Emulated HUE Bridge notification [Enable link mode] reappears every minute

### ISSUE THREAD

**Issue by pimw1** [hass-emulated-hue/core#242]
**Describe the bug**
Emulated HUE Bridge notification [Enable link mode] reappears every minute in Home Assistant. This happens when updating from version 2021.11 to 2021.12.0b0. The Emulated Hue docker container is running on a different raspberry 4 as compared to Home Assistant. I did not change a single thing on the Raspberry Pi 4 that is running Emulated Hue. I just updated Home Assistant on the other Raspberry pi 4. Normally, updates of Home Assistant are going smoothly.

**Steps to Reproduce**

**Expected behavior**
Same as in version 2021.11: it should just show once, not every minute.

**Logs**

'''
Emulated HUE Bridge
Click the link below to enable pairing mode on the virtual bridge:

Enable link mode
'''

**Hardware Info:**
 - Architecture (Ex: x86, ARM): ArmV7 
 - Addon version (Ex: stable or dev): stable, v.0.2.9
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): Raspbian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspbbery Pi 4

**Additional context**

See also the github issue for Home Assistant Core. I was not sure whether i should create the issue here or there: https://github.com/home-assistant/core/issues/61022

**Comment by marcelveldt** [comment]
This probably happens because the emulated Hue bridge is being detected by HA discovery and HA wants to connect.
I'll have to confirm though.

Can you check within Integrations if it discovered a Hue bridge there (which happens to be your emulated Hue ?

BTW: please close the duplicated issue in HA core. This is a (custom) integration issue.

Thanks!

**Comment by pimw1** [comment]
Hi, i can see it in my "ignored list" within the integrations page: 
![image](https://user-images.githubusercontent.com/74881023/144727713-a09284c5-26b5-4a0a-a000-7291e5780f0d.png)

I don't have any other active integrations that are related to this.
I've closed the other issue.

**Comment by marcelveldt** [comment]
Hmmm, something is still discovering the Emulated Hue then. I'm replying here as I have been involved with this project before @alexyao2015 took over and I'm involved in the HA core Hue integration which we just rewrote to the V2 API.

I'll quickly try to reproduce the issue myself to spot where the issue is caused.

**Comment by pimw1** [comment]
Thanks Marcel. If there is anything i can do, please let me know. Tomorrow my availablity is somewhat limited due to celebrating Sinterklaas.

**Comment by marcelveldt** [comment]
OK, was easy to reproduce. Actually 2 issues. One is that the emulated bridge initiates the link procedure too fast (when it's discovered instead of when a link attempt is made). On the other hand the HA zeroconf discovery seems to ping the bridge every few minutes even if you told it to ignore. I'll look into that too.

**Comment by marcelveldt** [comment]
Have fun with Sinterklaas btw ;-)

**Comment by pimw1** [comment]
Thanks!! And great to see you've discovered this so quick, awesome.

**Comment by pimw1** [comment]
The fix in 2021.12.0b1 works, thank you very much!
