### ISSUE TITLE
Throttling for HA API for Ambilight+Hue

### ISSUE THREAD

**Issue by Mr-Groch** [hass-emulated-hue/core#44]
I'm using zigbee2mqtt to control HA lights. When I enable Ambilight+Hue on my Philips TV with emulated Hue, I can see lot of not smooth color changes (instant changes). When I trace mqtt messages, I see that message is sended to lights 3-8 times per second with transition parameter from 0.03 to 0.08s as you can see on the screen from MQTT Explorer:

![image](https://user-images.githubusercontent.com/20594810/103447085-e8ccda00-4c86-11eb-919f-a5fa3c04d4ef.png)

It looks that this is too small amount for transition time, and transition is instant... I think also that throttling doesn't work in Ambilight+Hue mode (8 messages per second is way too much for non Hue bulbs I think...)

diyHue is behaving differently - transition is longer and smooth, and there is less noticable color changes, so color is little laggy comparing to TV ambilight but it feels much smoother

EDIT:
Also I noticed unhandled message in Zigbee2Mqtt sended on toggling Ambilight+Hue off:

`Publish 'set' 'effect' to 'Taśma LED RGBW - salon (prawa)' failed: 'Error: 'none' not allowed, choose between: blink,breathe,okay,channel_change,finish_effect,stop_effect'`

**Comment by marcelveldt** [comment]
I've tested with ZHA lights and ESPHome driven LED strips and that worked very smooth without throttling (so all packets are sent to the lights). In your case I think throttling is needed for smoother results.

Do you have access to the data directory ? There's a file in there called emulated_hue.json.
Each light has a config in that file and a setting called "entertainment_throttle".
The default is 0 (no throttling at all so send all packets to the light).

You can put a value in there in milliseconds. For example start with 500 and see what it brings and decrease until it is less attractive.

Remember to stop the emulator before you make changes to the file, otherwise they'll be overwritten.

Please let me know the results so we can set those as default for a zigbee2mqtt light

**Comment by Mr-Groch** [comment]
I've set `"entertainment_throttle": 500` to those 2 lights I'm using with Ambilight+Hue but that didn't make any difference... Offcourse I've resstarted addon and checked if my new values are still there ;)

Still I see mqtt messege each 0.07s to 0.2s with same transition values...

Oh - my non Android Philips TV doesn't use entertainment mode for Ambilight+Hue... It just keeping puting light set messages, for example I see lot of this in Emulated Hue log:

```
2021-01-01 23:58:52,214 DEBUG emulated_hue.api -- [192.168.1.125] PUT /api/550a2fa9c65448dca682/lights/17/state
2021-01-01 23:58:52,216 DEBUG emulated_hue.api -- {'xy': [0.26169338822364807, 0.20043809711933136], 'transitiontime': 10}
```

**Comment by marcelveldt** [comment]
Ah, that explains it. Your TV has the first version of Ambilight+Hue which doesn't utilize the entertainment mode.
It is really strange because your TV sends transitiontime of 10 (which is 10*100ms = 1 second) while you see a transitiontime 0f 0.3 in your zigbee2mqtt logs. So somewhere in the path that transitiontime got changed.

I'll have a quick look at zigbee2mqtt's internals if I can spot what's going on.

**Comment by Mr-Groch** [comment]
That's independent examples, but I see correlation - if in emulated_hue is `'transitiontime': 10` then in mqtt message I see `"transition": 0.1`; if in emulated_hue is `'transitiontime': 7` then in mqtt message I see `"transition": 0.07`; and so on...

**Comment by marcelveldt** [comment]
OK, so that is correct. Maybe diyhue alters the messages and sends another transitiontime instead. We just forward the messages as-is to Home Assistant

**Comment by Mr-Groch** [comment]
diyHue divides transition values by 10:

`            state['transition'] = value / 10`

https://github.com/diyhue/diyHue/blob/dfc6c158e14a1789eb446f98e1186356103bff90/BridgeEmulator/protocols/mqtt.py#L69

So 'transitiontime': 10 will be `"transition": 1` in mqtt message; `'transitiontime': 7` will be `"transition": 0.7`, and so on...

**Comment by marcelveldt** [comment]
we do too:

https://github.com/marcelveldt/hass_emulated_hue/blob/master/emulated_hue/api.py#L625

**Comment by Mr-Groch** [comment]
Yes, but here is dividing by 100 not by 10:

`transitiontime = request_data[const.HUE_ATTR_TRANSITION] / 100`

**Comment by marcelveldt** [comment]
Oops, your are correct. Can you adjust that on your dev setup to see if it solves the issue ?

**Comment by marcelveldt** [comment]
I've checked in the change btw and will trigger a new docker build

**Comment by Mr-Groch** [comment]
Transition is now smooth after changing division to 10, so this fixes choppy color changes. But I have second request - can You please add throttling also for standard api? Not only for entertainment mode? I see that sometimes on dynamic scenes it can generate to 15-20 messages per second! That has negative impact on performance not only on emulated_hue but whole HA and other addons...

**Comment by marcelveldt** [comment]
Sure, I think that will be possible but it will require some tinkering. What hardware do you run HA on?

**Comment by Mr-Groch** [comment]
Thanks in advice! I'm running on Raspberry Pi 3

**Comment by marcelveldt** [comment]
Ah yes, that explains it I guess. I was testing with several ZHA and ESPHome lights in entertainment mode (20+ messages per second to each light) and I did not notice any delays or performance issues but HA is running on a NUC in my case. 

I'll implement some basic throttling and let you know.

**Comment by alexyao2015** [comment]
As a side note, you may want to look into better hardware as the hue api is generally pretty resource intensive with large amounts of packets being sent. An old laptop or desktop may do wonders.

**Comment by Mr-Groch** [comment]
I've changed topic to better describe to what this issue transformed currently :)
