### ISSUE TITLE
Support Yeelight

### ISSUE THREAD

**Issue by alexyao2015** [hass-emulated-hue/core#80]
**Describe the bug**

Yeelight suffers from rate limits when using the standard light.turn_on service that other integrations use. When enabling music mode, it requires usage of its own services for control.

`YEELIGHT.SET_COLOR_SCENE`
Used for setting RGB color and automatically turns on the light.

`YEELIGHT.SET_HSV_SCENE`
Used for HSV color and automatically turns on the light.

`YEELIGHT.SET_COLOR_TEMP_SCENE`
Used for CT color and automatically turns on the light.

Lights are still turned on/off using the default light.turn_on and light.turn_off service. 

We must
1. Detect that the device is Yeelight.
2. Automatically determine the correct service to use. 

**Steps to Reproduce**

**Expected behavior**

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

**Comment by alexyao2015** [comment]
If only brightness is changed, we will have to resort to the default `light.turn_on` service.

This should be fine for entertainment mode during flashes as rgb data is still sent, so we shouldn't face any rate limits there.

**Comment by zewelor** [comment]
Hmm not sure why its necessary to use this services, while in music mode, to change colors ? I've tested following: Turn on music mode for bulb, change color few times, turn off music mode. Color changed as expected, using turn_on. Using this services, could have small advantage, to skip resend turn_on ( yeelight command ) to light, each time color changes.

**Comment by alexyao2015** [comment]
From my testing, I've found that using `light.turn_on` effectively ignores music mode and results in Yeelight being subject to the rate limit. You can test it yourself by simply moving around the RGB color wheel and you'll notice that pretty quickly, the color stops changing. Entertainment is the same, it works for the first few seconds before freezing in place. All light commands no longer work from HA (you can try turning the light on and off and it will not work).

Maybe this is an issue for HA?

**Comment by zewelor** [comment]
How did you turn on music mode ? Newest HA version, has device property for music mode. Can you verify, that its set to true, on light card ? That's doesn't sound right at all, which light are you using ? From turn_on ha method, it doesn't change anything, if light is in music mode or not. It cannot bypass music mode on its own ( when light is in music mode, it is in music mode, and only one device can control it ).

**Comment by alexyao2015** [comment]
I'm running the latest 2021.1.3 version and do not see a music mode property when opened. See the screenshot below. Yeelight config was added through the yaml. We currently only send light.turn_on requests when changing a light's properties which is true for normal and entertainment mode. Simply quickly moving over the rgb color wheel in the Hue app, turning on entertainment mode, or quickly turning the light on and off in HA, results in it hitting the rate limits. When the limits are hit, the light no longer responds to any commands.

Would be great if you could take a look at it!

```yaml
yeelight:
  devices:
    ip_address:
      name: Side Lamp
      transition: 0
      use_music_mode: true
```

![Capture](https://user-images.githubusercontent.com/33379584/104821946-72df7b80-580d-11eb-8f44-981547cd6832.PNG)

**Comment by alexyao2015** [comment]
Btw, whats the purpose of having separate services for Yeelight if light.turn_on should be able to achieve the same thing?

**Comment by zewelor** [comment]
Thanks for additional context:

1. Looks I was wrong, about music mode property, its still not in latest version, should be in next ( PR missed merge window for this release ). I'm using my own version for yeelight component, with this PR merged, so thats why I was confused. If you want to debug it more, and play more with music mode, you could use files from this PR: https://github.com/home-assistant/core/pull/44533/files as custom component. This way you can also change music mode via service call.
2. From what I can gather, in your case light didn't enter music mode. I've tried to recreate that and looks like setting music_mode in yaml doesn't work. ( Or at least in some cases ). Not sure how yaml vs config flow are handed now in yeelight ( as someone other rewrote that part ). Best would be to remove yaml config for yeelight, and add it via config ui ( Integrations ). There you can turn on music mode, and I've tested it now and should work as expected.
3. That separate services are implemented, because they are different yeelight API commands. There is command to change rgb color ( which is used by turn_on ), and there is other command to set rgb scene. From what I understand, "scene" commands all turns on light, in one call. So the main difference is, when using turn_on, HA sends 2-3 commands to the light. First to turn light on, then change brightness and third to change color. When using set scene services ( which uses different yeelight API command ), light gets only single command, with brightness and color, it also turns the light on. ( More can be found here: https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf ). 
4. From user point of view, there is little difference. Mainly difference is visible when for example, light was 100% brigthness cold white, then turned off, and then you want to turn in on, to dim red, for example. When used via turn_on, you need to send 3 commands, with turn on being first one. If there will be some delay on wifi / bulb processing commands etc, What you can see is short "flash" in color / brightness ( because bulb first turns on to 100% white, or any other color / brightness used previously ). Then there is command to dim to red. Thats where advantage of set_scene commands shines. Using them, you only send single command to yeelight, and it gets turned on at requested color / brightness. Without any weird color / brigthess flashes, that might occur with turn_on.
5. If its possible, to use other service, for emulated hue with yeelight, it might be good to test performance of set_scene service calls vs turn_on. Not sure which one is faster, also if using set_scene commands works 100% stable while in music mode. From my understanding yeelight app is not using this set_scene methods, for music_mode in app. So its possible they wont work reliable.

**Comment by zewelor** [comment]
As for detecting yeelight, and using custom services. I'm thinking maybe it would be good to create some small HA component, which will provide HA.turn_on wrapper for lights. This way emulated_hue could use that new service call, and doesn't need to bloat its code with various integration, cases etc. Component can check light domains, and load some specific handling on its own ? Like skip turn_on, and use set_scene for yeelight. Also on turning on entertaiment mode, do some setup, like turning on music mode. It could also provide like sensors for emulated_hue, for example how entertaiment mode being active, or whats currently controlling lights, etc ?

**Comment by alexyao2015** [comment]
Hi again. 

I've take a look at the api documentation, and it seems that set_scene should do everything a user would need. It turns on the light if not already on, sets the color and brightness. In the case that a turn_on service is called for yeelight, it should check if brightness and a color type has been provided. If so, it should automatically use set_scene, instead of sending 3 packets. 

If this were handled automatically by light.turn_on, it would allow for deprecation of the scene commands and reduce confusion. 

If music mode is enabled, would turning the light on and off bypass music mode as those are power commands or is that also sent through music mode? I'll need to give that another try when using the UI for the config. Maybe take a look at why the yaml config isn't working in the meantime? Lastly, is there some way to rename the bulb shown in the integrations? I've tried renaming the device itself, but it still shows the original name of yeelight_ some random characters.

**Comment by alexyao2015** [comment]
@zewelor It seems like music mode is bugged or yeelight just can't handle rapid updates. Just updated to the dev version so I would be able to see music mode on the card. It's now showing as true, but the moment I turn on entertainment, the light locks up for a bit, similar to how it would lock up when music mode is disabled. Not sure if music mode was not properly implemented or if something else is happening. This is a development instance of HASS, so it's a pretty barebones install with nothing interfering.

**Comment by zewelor** [comment]
Which light are you using ? Which fw ? Does light have internet connection ? I've got few 1st gen light bulbs and they work fine on music mode. Can you try music mode via yeelight app ? It would be good to turn on debug logging and maybe find some clues there. When light locks up, does it renders unavailable in HA ?

**Comment by zewelor** [comment]
As for using set scene in turn_on, I don't think something that could be done in HA core. From my understanding idea is to have turn_on using most basic commands, to be as most compatible as possible. I think easier route would be to make some generic light service, which could be implemented via each integration, and it would be used to fast light sync. But it would involve some design decisions. Second thing would be to create small component, which would use best way to fast control light, depending on integration ?

As for renaming light, its best done via integrations UI. I don't think its possible now to change it via yaml. I will write to guy who wrote config flow for yeelight, if we can drop yaml configuration, as its clearly broken now and confusing.

**Comment by alexyao2015** [comment]
@zewelor 

I'm using a v2 color bulb. Purchased it 2 years ago think. Its running the latest firmware which I believe is 2.0.6_0065.  Music mode definitely works fine on the yeelight app. When the light locks up, it still shows as available. Are you able to reproduce it? I can reproduce this issue very consistently on a clean HASS instance. 

I found a bug with the yeelight integration. It seems to change the rgb color wheel when you change the light temperature instead of staying in the center when adjusting the temperature. This is problematic as say setting the color temp to anything warmer than max daylight will result in the rgb color wheel being adjusted. This means that HASS will send data to yeelight sending first the CT then the RGB, resulting in substantially lower brightness values. This effect is very visible when entering the scenes menu and adjusting lights, then trying to recall the scene. You will notice substantially different colors when the original state of the lights are recalled. RGB colors should not be sent in that case since it would switch color modes. Would be great it that could be fixed!

While the idea of a separate turn_on service seems great, I really think it should be integrated into HASS at this point as part of the default service.

Lastly, renaming works for the device, but its still showing the original name in the integrations menu. In other areas of HASS, it shows the correct name.

**Comment by alexyao2015** [comment]
After some testing, this seems to be a non-issue in the latest version of home assistant.
